#!/bin/bash

energy=$(cat /sys/class/power_supply/BAT0/energy_now)

full=$(cat /sys/class/power_supply/BAT0/energy_full)

out=$(cat /sys/class/power_supply/BAT0/power_now | awk -v full=$full -v energy=$energy '{print ((full - energy)*10^-6)/($0*10^-6), "Hours remaining"}')

dunstify -a "Battery" -u low -r "991055" "$out"


